apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: xp-gcp-sql
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    databaseVersion: POSTGRES_14
    region: europe-north1
    settings:
      tier: db-custom-1-3840
      dataDiskSizeGb: 10
  providerConfigRef:
    name: gcp-provider-config
  writeConnectionSecretToRef:
    name: xp-cloudsql-connection-details
    namespace: crossplane-system