apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-account-creds
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCWrikjta8X2RQLQ/a1U2NJoNq2trBZFXYVrtkwIp7KNHjkq0ezp+n2nvJBx/PiIeG3osdtNB7PomOfrYx0qQ2WfXaiWDAj8JxbO6Lz1eRlFL08sKUNpIRaX+3yzxrkB9bo1cx8hvQtEjyT1qtjXf5io07zPFGArHMay0ATwWsdEKQGh6K2sCxKyHJNsvzOYQv85bujDtvmZJVi0DPuFUZH/AHPz7uOdcPddEpLCrcD2S9KHyfvzDYrW45NTWaDeta1xva7gEmPs8H3sznnRKd71oZY4xfaohh2Ed+X2JEo8hlUYOy5Ikl1K1NwcD5XoIpvKJrCK5YCTgm31MhUsHsdhoIUPFQ5VB+gUB89xIZPzNHcFTE+dhy2xAjA73Xk5HjowfCjEeH0i02FfjqSeLC1T+bC0x9t9uM+TpDr3RDNyXGEELnhXouuNUrHfKa+3T3NKbiti3F/BR25RLPoWHbpwLSiNeEObtdMEXaMQQDN9mu8ZCGLsEzNXwOK+Z1DLnv+uuTQZbsDRd4RN+cLOAkwRbmS/o1Yn30IYmjfauiectGWnDJtYCfTeVrEU0FVSq2/pKHnI6E4pgDyINljGQdaVSMDgNudX1gKj8maMgHI6eojocUdL/7L7b80Jg8utsbJr0EzNNWiWlPAmhQJywIfG0buR8OhMrSyvOXJTewlaAHXDc4WojybEzKQRhnyhps7MUmXHvYDuq24uR8zh+6R438kTnfWqikehNIqYxfQQSYnWds7rPpB/VrXoBvWFbLNKyw30DLT8GMWrbDuEBysYb+yGc+Y55PEp9Ci18kGWczQRQ1ba3zIChYDwZtKpMjs1IzkxNrEYe9ca/DgmS5AZh7+QQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-account-creds
      namespace: crossplane-system
    type: Opaque

