apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: gcp-account-creds
      namespace: crossplane-system
      key: credentials
  projectID: crossplane-2022