apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true 
spec:
  package: "crossplane/provider-azure:v0.18.1"