apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-digitalocean
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true 
spec:
  package: "crossplane/provider-digitalocean:v0.1.0"
