apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true 
spec:
  package: "crossplane/provider-gcp:v0.21.0"