apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: config
    server: 'https://kubernetes.default.svc'
  source:
    path: ./config
    repoURL: 'https://github.com/Al-HusseinHameedJasim/gitopscon-europe-2022'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
